apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-container
  template:
    metadata:
      labels:
        app: flask-container
    spec:
      containers:
        - name: flask-web
          image: realbtotharye/flask-starter
          ports:
            - containerPort: 8000